name: Unit Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python-version: "3.9"
            environment: [test]
          - os: ubuntu-latest
            python-version: "3.10"
            environment: [test]
          - os: ubuntu-latest
            python-version: "3.11"
            environment: [test]
          - os: ubuntu-latest
            python-version: "3.12"
            environment: [test]
          - os: windows-latest
            python-version: "3.11"
            environment: [test]
          - os: macos-latest
            python-version: "3.10"
            environment: [test]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.0
        with:
          pixi-version: v0.40.1
          auth-host: prefix.dev
          auth-token: ${{ secrets.PREFIX_DEV_TOKEN }}

      - name: Run Tests
        run: pixi run -e ${{ matrix.environment }} test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: donlapark/coverforest
