name: Unit Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python-version: "3.7"
            numpy-version: 1.21.4
          - os: ubuntu-latest
            python-version: "3.8"
            numpy-version: 1.21.4
          - os: ubuntu-latest
            python-version: "3.9"
            numpy-version: 1.21.4
          - os: ubuntu-latest
            python-version: "3.10"
            numpy-version: 1.22.4
          - os: ubuntu-latest
            python-version: "3.11"
            numpy-version: 1.25.2
          - os: windows-latest
            python-version: "3.11"
            numpy-version: 1.25.2
          - os: macos-latest
            python-version: "3.10"
            numpy-version: 1.25.2
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.0
        with:
          pixi-version: v0.40.1
          cache: true
          auth-host: prefix.dev
          auth-token: ${{ secrets.PREFIX_DEV_TOKEN }}

      - name: Install numpy
        run: pip install numpy=${{ matrix.numpy-version }}

      - name: Run tests
        run: pixi run -e ${{ matrix.environment }} test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.6.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: donlapark/coverforest
